(() => {
  'use strict';

  const canvas = document.getElementById('game');
  const ctx = canvas.getContext('2d');
  const $ = (id) => document.getElementById(id);
  const screens = { menu: $('menu'), instructions: $('instructions'), settings: $('settings'), pause: $('pause'), gameOver: $('gameOver') };
  const ui = { hud: $('hud'), score: $('score'), timer: $('timer'), combo: $('combo'), wave: $('wave'), health: $('health'), toast: $('toast'), flash: $('hitFlash'), best: $('bestScore'), rating: $('menuRating'), finalScore: $('finalScore'), finalTime: $('finalTime'), finalKills: $('finalKills'), finalCombo: $('finalCombo'), finalAccuracy: $('finalAccuracy'), newRecord: $('newRecord'), resultKicker: $('resultKicker'), resultTitle: $('resultTitle'), touch: $('touchControls') };
  const TAU = Math.PI * 2;
  const store = { get(key, fallback) { try { const value = localStorage.getItem(`atc-${key}`); return value === null ? fallback : JSON.parse(value); } catch (_) { return fallback; } }, set(key, value) { try { localStorage.setItem(`atc-${key}`, JSON.stringify(value)); } catch (_) {} } };
  const settings = { sound: store.get('sound', true), motion: store.get('motion', false), difficulty: store.get('difficulty', 'calm') };
  const state = { screen: 'menu', score: 0, time: 60, health: 100, wave: 1, combo: 1, bestCombo: 1, comboClock: 0, kills: 0, shots: 0, hits: 0, elapsed: 0, spawnClock: 0, powerClock: 0, shake: 0, flash: 0, newRecord: false };
  const input = { keys: new Set(), pointer: { x: 0, y: 0, down: false }, move: { x: 0, y: 0 }, touchId: null, fireTouch: false };
  const player = { x: 0, y: 0, radius: 15, speed: 310, fireClock: 0, dashClock: 0, invincible: 0, aim: 0 };
  let width = 0, height = 0, dpr = 1, lastTime = 0, audioContext = null, toastTimer = 0;
  let enemies = [], projectiles = [], particles = [], popups = [], powerups = [];

  function resize() { dpr = Math.min(window.devicePixelRatio || 1, 2); width = window.innerWidth; height = window.innerHeight; canvas.width = width * dpr; canvas.height = height * dpr; canvas.style.width = `${width}px`; canvas.style.height = `${height}px`; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); if (!player.x) { player.x = width / 2; player.y = height / 2; } }
  function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function random(min, max) { return min + Math.random() * (max - min); }
  function distance(a, b) { return Math.hypot(a.x - b.x, a.y - b.y); }
  function formatScore(score) { return Math.max(0, Math.floor(score)).toString().padStart(6, '0'); }
  function difficultyScale() { return settings.difficulty === 'overdrive' ? 1.35 : settings.difficulty === 'surge' ? 1.16 : 1; }
  function difficultyLabel() { return settings.difficulty === 'overdrive' ? 'OVERDRIVE' : settings.difficulty === 'surge' ? 'SURGE' : 'CALM'; }

  function beep(frequency, duration, type = 'sine', volume = .04) {
    if (!settings.sound) return;
    try {
      audioContext ||= new (window.AudioContext || window.webkitAudioContext)();
      if (audioContext.state === 'suspended') audioContext.resume();
      const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain();
      oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, audioContext.currentTime); oscillator.frequency.exponentialRampToValueAtTime(Math.max(40, frequency * .55), audioContext.currentTime + duration);
      gain.gain.setValueAtTime(volume, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + duration);
      oscillator.connect(gain); gain.connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + duration);
    } catch (_) {}
  }
  const sounds = { click: () => beep(360, .06, 'square', .025), shoot: () => beep(520, .045, 'square', .02), hit: () => beep(180, .08, 'sawtooth', .035), kill: () => beep(740, .1, 'triangle', .035), pickup: () => { beep(580, .07, 'sine', .03); setTimeout(() => beep(880, .1, 'sine', .025), 50); }, damage: () => beep(90, .22, 'sawtooth', .045), combo: () => beep(980, .12, 'triangle', .04) };

  function setScreen(name) { Object.entries(screens).forEach(([key, element]) => element.classList.toggle('hidden', key !== name)); state.screen = name; ui.hud.classList.toggle('hidden', name !== 'playing' && name !== 'paused'); }
  function showToast(message) { ui.toast.textContent = message; ui.toast.classList.remove('show'); void ui.toast.offsetWidth; ui.toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => ui.toast.classList.remove('show'), 1100); }
  function syncMenu() { const best = store.get('best', 0); ui.best.textContent = formatScore(best); ui.rating.textContent = best > 18000 ? 'ELITE' : best > 9000 ? 'RISING' : best ? 'ROOKIE' : 'UNRANKED'; }
  function syncSettings() { $('soundToggle').classList.toggle('active', settings.sound); $('soundToggle').setAttribute('aria-pressed', settings.sound); $('motionToggle').classList.toggle('active', settings.motion); $('motionToggle').setAttribute('aria-pressed', settings.motion); document.querySelectorAll('[data-difficulty]').forEach(button => button.classList.toggle('active', button.dataset.difficulty === settings.difficulty)); }

  function startGame() {
    sounds.click(); setScreen('playing'); ui.touch.classList.toggle('hidden', !('ontouchstart' in window));
    state.score = 0; state.time = 60; state.health = 100; state.wave = 1; state.combo = 1; state.bestCombo = 1; state.comboClock = 0; state.kills = 0; state.shots = 0; state.hits = 0; state.elapsed = 0; state.spawnClock = .8; state.powerClock = 12; state.shake = 0; state.newRecord = false;
    enemies = []; projectiles = []; particles = []; popups = []; powerups = []; player.x = width / 2; player.y = height / 2; player.fireClock = 0; player.invincible = 0; input.keys.clear(); showToast('READY? 60 SECONDS'); updateHud();
  }
  function finishGame() {
    if (state.screen !== 'playing' && state.screen !== 'paused') return;
    const previousBest = store.get('best', 0); state.newRecord = state.score > previousBest; if (state.newRecord) store.set('best', Math.floor(state.score));
    ui.finalScore.textContent = formatScore(state.score); ui.finalTime.textContent = `${(60 - state.time).toFixed(1)}s`; ui.finalKills.textContent = state.kills; ui.finalCombo.textContent = `x${state.bestCombo}`; ui.finalAccuracy.textContent = `${state.shots ? Math.round(state.hits / state.shots * 100) : 0}%`; ui.newRecord.classList.toggle('hidden', !state.newRecord);
    const completed = state.time <= 0 && state.health > 0; ui.resultKicker.textContent = completed ? 'TRIAL COMPLETE' : 'CORE COLLAPSE'; ui.resultTitle.innerHTML = completed ? 'You bent<br><em>the clock.</em>' : 'The clock<br><em>won.</em>'; sounds[completed ? 'combo' : 'damage'](); setScreen('gameOver'); syncMenu();
  }
  function updateHud() { ui.score.textContent = formatScore(state.score); ui.timer.textContent = Math.max(0, state.time).toFixed(1); ui.combo.textContent = `x${state.combo}`; ui.wave.textContent = String(state.wave).padStart(2, '0'); ui.health.style.width = `${state.health}%`; }

  function spawnEnemy(forceType) {
    const edge = Math.floor(Math.random() * 4); const margin = 50; let x = edge === 0 ? -margin : edge === 1 ? width + margin : random(0, width); let y = edge === 2 ? -margin : edge === 3 ? height + margin : random(0, height);
    const roll = Math.random(); const type = forceType || (state.elapsed > 22 && roll < .18 ? 'splitter' : state.elapsed > 8 && roll < .42 ? 'hunter' : 'drifter'); const scale = difficultyScale();
    const data = type === 'hunter' ? { radius: 18, speed: random(92, 132) * scale, hp: 2, color: '#ff684d', points: 180 } : type === 'splitter' ? { radius: 21, speed: random(48, 70) * scale, hp: 3, color: '#a98dff', points: 260 } : { radius: 13, speed: random(56, 86) * scale, hp: 1, color: '#55d7c8', points: 100 };
    enemies.push({ x, y, vx: 0, vy: 0, type, hit: 0, ...data });
  }
  function spawnPowerup() { const types = ['time', 'repair', 'overdrive']; const type = types[Math.floor(Math.random() * types.length)]; powerups.push({ x: random(90, width - 90), y: random(120, height - 90), type, life: 10, pulse: 0 }); }
  function fire() {
    if (state.screen !== 'playing' || player.fireClock > 0) return;
    const target = input.fireTouch && enemies.length ? enemies.reduce((nearest, enemy) => distance(enemy, player) < distance(nearest, player) ? enemy : nearest, enemies[0]) : input.pointer;
    const angle = Math.atan2(target.y - player.y, target.x - player.x); player.aim = angle; player.fireClock = .16; state.shots++; projectiles.push({ x: player.x + Math.cos(angle) * 19, y: player.y + Math.sin(angle) * 19, vx: Math.cos(angle) * 690, vy: Math.sin(angle) * 690, life: .9, radius: 4 }); addParticles(player.x + Math.cos(angle) * 15, player.y + Math.sin(angle) * 15, '#d8ff45', 4, 80); sounds.shoot(); }
  function dash() { if (player.dashClock > 0 || state.screen !== 'playing') return; const x = movementAxis('x'); const y = movementAxis('y'); const length = Math.hypot(x, y) || 1; player.x = clamp(player.x + x / length * 105, 25, width - 25); player.y = clamp(player.y + y / length * 105, 90, height - 25); player.invincible = .28; player.dashClock = 2.5; addParticles(player.x, player.y, '#a98dff', 16, 150); sounds.click(); }
  function movementAxis(axisName) { const positive = axisName === 'x' ? ['ArrowRight', 'd'] : ['ArrowDown', 's']; const negative = axisName === 'x' ? ['ArrowLeft', 'a'] : ['ArrowUp', 'w']; return (positive.some(key => input.keys.has(key)) ? 1 : 0) - (negative.some(key => input.keys.has(key)) ? 1 : 0) + (axisName === 'x' ? input.move.x : input.move.y); }

  function update(dt) {
    if (state.screen !== 'playing') return;
    state.elapsed += dt; state.time -= dt; state.spawnClock -= dt; state.powerClock -= dt; state.comboClock -= dt; player.fireClock -= dt; player.dashClock -= dt; player.invincible -= dt; state.shake = Math.max(0, state.shake - dt * 20);
    state.wave = 1 + Math.floor(state.elapsed / 12);
    const moveX = movementAxis('x'); const moveY = movementAxis('y'); const moveLength = Math.hypot(moveX, moveY) || 1; player.x = clamp(player.x + moveX / moveLength * player.speed * dt, 25, width - 25); player.y = clamp(player.y + moveY / moveLength * player.speed * dt, 95, height - 25);
    if (input.pointer.down || input.keys.has(' ') || input.fireTouch) fire();
    if (state.spawnClock <= 0) { const count = Math.min(3, 1 + Math.floor(state.elapsed / 25)); for (let i = 0; i < count; i++) spawnEnemy(); state.spawnClock = Math.max(.32, .95 - state.elapsed * .006) / difficultyScale(); }
    if (state.powerClock <= 0) { spawnPowerup(); state.powerClock = random(13, 19); }
    updateProjectiles(dt); updateEnemies(dt); updatePowerups(dt); updateParticles(dt); updatePopups(dt);
    if (state.comboClock <= 0 && state.combo > 1) { state.combo = Math.max(1, state.combo - dt * 2); }
    if (state.time <= 0 || state.health <= 0) finishGame(); updateHud();
  }
  function updateProjectiles(dt) { projectiles = projectiles.filter(p => { p.x += p.vx * dt; p.y += p.vy * dt; p.life -= dt; for (let index = enemies.length - 1; index >= 0; index--) { const enemy = enemies[index]; if (distance(p, enemy) < p.radius + enemy.radius) { enemy.hp--; enemy.hit = .12; p.life = 0; state.hits++; addParticles(p.x, p.y, enemy.color, 6, 100); sounds.hit(); if (enemy.hp <= 0) destroyEnemy(index); break; } } return p.life > 0 && p.x > -30 && p.x < width + 30 && p.y > 70 && p.y < height + 30; }); }
  function destroyEnemy(index) { const enemy = enemies[index]; enemies.splice(index, 1); state.kills++; state.comboClock = 2.4; state.combo = clamp(state.combo + .35, 1, 9.99); state.bestCombo = Math.max(state.bestCombo, Math.floor(state.combo)); const points = Math.round(enemy.points * state.combo); state.score += points; popups.push({ x: enemy.x, y: enemy.y, text: `+${points}`, color: state.combo >= 3 ? '#d8ff45' : '#dce9dc', life: 1 }); addParticles(enemy.x, enemy.y, enemy.color, enemy.type === 'splitter' ? 22 : 14, 170); sounds.kill(); if (Math.floor(state.combo) >= 3 && Math.floor(state.combo) % 2 === 0) { showToast(`${Math.floor(state.combo)}x CHAIN`); sounds.combo(); } if (enemy.type === 'splitter') { for (let i = 0; i < 2; i++) { const child = { x: enemy.x + random(-8, 8), y: enemy.y + random(-8, 8), vx: 0, vy: 0, type: 'drifter', hit: 0, radius: 8, speed: 105, hp: 1, color: '#d9b9ff', points: 80 }; enemies.push(child); } } }
  function updateEnemies(dt) { enemies.forEach(enemy => { const angle = Math.atan2(player.y - enemy.y, player.x - enemy.x); const turn = enemy.type === 'hunter' ? .95 : .45; enemy.vx += Math.cos(angle) * enemy.speed * turn * dt; enemy.vy += Math.sin(angle) * enemy.speed * turn * dt; const velocity = Math.hypot(enemy.vx, enemy.vy) || 1; enemy.vx = enemy.vx / velocity * enemy.speed; enemy.vy = enemy.vy / velocity * enemy.speed; enemy.x += enemy.vx * dt; enemy.y += enemy.vy * dt; enemy.hit -= dt; if (distance(enemy, player) < enemy.radius + player.radius) { enemy.x -= Math.cos(angle) * 8; enemy.y -= Math.sin(angle) * 8; if (player.invincible <= 0) { player.invincible = .9; state.health -= enemy.type === 'hunter' ? 24 : 16; state.combo = 1; state.comboClock = 0; state.shake = 12; ui.flash.classList.remove('flash'); void ui.flash.offsetWidth; ui.flash.classList.add('flash'); addParticles(player.x, player.y, '#ff684d', 15, 140); sounds.damage(); } } }); }
  function updatePowerups(dt) { powerups = powerups.filter(power => { power.life -= dt; power.pulse += dt * 4; if (distance(power, player) < 28) { if (power.type === 'time') { state.time = Math.min(60, state.time + 5); state.score += 400; showToast('+5 SECONDS'); } if (power.type === 'repair') { state.health = Math.min(100, state.health + 30); showToast('CORE REPAIRED'); } if (power.type === 'overdrive') { state.combo = Math.min(9.99, state.combo + 2); state.score += 700; showToast('CHAIN SURGE'); } addParticles(power.x, power.y, powerColor(power.type), 18, 130); sounds.pickup(); return false; } return power.life > 0; }); }
  function powerColor(type) { return type === 'time' ? '#d8ff45' : type === 'repair' ? '#55d7c8' : '#a98dff'; }
  function addParticles(x, y, color, count, speed) { for (let i = 0; i < count; i++) { const angle = random(0, TAU); const velocity = random(speed * .25, speed); particles.push({ x, y, vx: Math.cos(angle) * velocity, vy: Math.sin(angle) * velocity, life: random(.25, .75), max: .75, size: random(1, 3), color }); } }
  function updateParticles(dt) { particles = particles.filter(p => { p.x += p.vx * dt; p.y += p.vy * dt; p.vx *= .97; p.vy *= .97; p.life -= dt; return p.life > 0; }); }
  function updatePopups(dt) { popups = popups.filter(p => { p.y -= 26 * dt; p.life -= dt; return p.life > 0; }); }

  function draw() { ctx.clearRect(0, 0, width, height); ctx.save(); if (state.shake > 0 && !settings.motion) ctx.translate(random(-state.shake, state.shake), random(-state.shake, state.shake)); drawArena(); powerups.forEach(drawPowerup); projectiles.forEach(drawProjectile); enemies.forEach(drawEnemy); drawPlayer(); particles.forEach(drawParticle); popups.forEach(drawPopup); ctx.restore(); }
  function drawArena() { const gradient = ctx.createRadialGradient(width / 2, height / 2, 0, width / 2, height / 2, Math.max(width, height) * .65); gradient.addColorStop(0, 'rgba(29,70,74,.22)'); gradient.addColorStop(1, 'rgba(3,10,14,0)'); ctx.fillStyle = gradient; ctx.fillRect(0, 0, width, height); ctx.strokeStyle = 'rgba(216,255,69,.055)'; ctx.lineWidth = 1; const spacing = 48; const offset = (state.elapsed * 12) % spacing; for (let x = -spacing; x < width + spacing; x += spacing) { ctx.beginPath(); ctx.moveTo(x + offset, 75); ctx.lineTo(x + offset, height); ctx.stroke(); } for (let y = 75; y < height; y += spacing) { ctx.beginPath(); ctx.moveTo(0, y + offset); ctx.lineTo(width, y + offset); ctx.stroke(); } ctx.strokeStyle = 'rgba(216,255,69,.16)'; ctx.strokeRect(24, 94, width - 48, height - 118); }
  function drawPlayer() { ctx.save(); ctx.translate(player.x, player.y); ctx.rotate(player.aim); ctx.globalAlpha = player.invincible > 0 && Math.floor(player.invincible * 14) % 2 ? .3 : 1; ctx.shadowBlur = 22; ctx.shadowColor = '#d8ff45'; ctx.fillStyle = '#d8ff45'; ctx.beginPath(); ctx.moveTo(20, 0); ctx.lineTo(-13, -12); ctx.lineTo(-8, 0); ctx.lineTo(-13, 12); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#07131a'; ctx.beginPath(); ctx.arc(1, 0, 4, 0, TAU); ctx.fill(); ctx.restore(); }
  function drawEnemy(enemy) { ctx.save(); ctx.translate(enemy.x, enemy.y); ctx.rotate(state.elapsed * (enemy.type === 'hunter' ? 2 : -1)); ctx.globalAlpha = enemy.hit > 0 ? .45 : 1; ctx.shadowBlur = enemy.type === 'hunter' ? 18 : 10; ctx.shadowColor = enemy.color; ctx.strokeStyle = enemy.color; ctx.lineWidth = 2; ctx.fillStyle = 'rgba(7,19,26,.9)'; ctx.beginPath(); if (enemy.type === 'hunter') { ctx.moveTo(enemy.radius, 0); ctx.lineTo(0, enemy.radius); ctx.lineTo(-enemy.radius, 0); ctx.lineTo(0, -enemy.radius); } else { const sides = enemy.type === 'splitter' ? 6 : 4; for (let i = 0; i < sides; i++) { const angle = i / sides * TAU; const x = Math.cos(angle) * enemy.radius; const y = Math.sin(angle) * enemy.radius; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } } ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.restore(); }
  function drawProjectile(p) { ctx.fillStyle = '#d8ff45'; ctx.shadowBlur = 14; ctx.shadowColor = '#d8ff45'; ctx.beginPath(); ctx.arc(p.x, p.y, p.radius, 0, TAU); ctx.fill(); ctx.shadowBlur = 0; }
  function drawPowerup(power) { const color = powerColor(power.type); const radius = 15 + Math.sin(power.pulse) * 3; ctx.save(); ctx.translate(power.x, power.y); ctx.strokeStyle = color; ctx.fillStyle = `${color}18`; ctx.shadowBlur = 20; ctx.shadowColor = color; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, radius, 0, TAU); ctx.fill(); ctx.stroke(); ctx.rotate(power.pulse); ctx.beginPath(); ctx.moveTo(0, -8); ctx.lineTo(7, 0); ctx.lineTo(0, 8); ctx.lineTo(-7, 0); ctx.closePath(); ctx.stroke(); ctx.restore(); }
  function drawParticle(p) { ctx.globalAlpha = Math.max(0, p.life / p.max); ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, p.size, p.size); ctx.globalAlpha = 1; }
  function drawPopup(p) { ctx.globalAlpha = Math.min(1, p.life * 2); ctx.fillStyle = p.color; ctx.font = '700 13px monospace'; ctx.textAlign = 'center'; ctx.fillText(p.text, p.x, p.y); ctx.globalAlpha = 1; }

  function pointerPosition(event) { const rect = canvas.getBoundingClientRect(); input.pointer.x = event.clientX - rect.left; input.pointer.y = event.clientY - rect.top; }
  window.addEventListener('resize', resize); window.addEventListener('blur', () => { if (state.screen === 'playing') pauseGame(); }); document.addEventListener('visibilitychange', () => { if (document.hidden && state.screen === 'playing') pauseGame(); });
  window.addEventListener('keydown', event => { input.keys.add(event.key); if ([' ', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(event.key)) event.preventDefault(); if (event.key === 'Escape') state.screen === 'playing' ? pauseGame() : state.screen === 'pause' ? resumeGame() : null; if (event.key === 'Shift') dash(); }); window.addEventListener('keyup', event => input.keys.delete(event.key)); canvas.addEventListener('pointermove', pointerPosition); canvas.addEventListener('pointerdown', event => { pointerPosition(event); input.pointer.down = true; }); window.addEventListener('pointerup', () => input.pointer.down = false);
  function pauseGame() { if (state.screen !== 'playing') return; sounds.click(); setScreen('pause'); }
  function resumeGame() { if (state.screen !== 'pause') return; sounds.click(); setScreen('playing'); }
  function bindTouch() { const pad = $('movePad'); let rect; pad.addEventListener('pointerdown', event => { input.touchId = event.pointerId; pad.setPointerCapture(event.pointerId); rect = pad.getBoundingClientRect(); updatePad(event); }); pad.addEventListener('pointermove', event => { if (event.pointerId === input.touchId) updatePad(event); }); pad.addEventListener('pointerup', () => { input.touchId = null; input.move.x = 0; input.move.y = 0; $('movePad').firstElementChild.style.transform = 'translate(0,0)'; }); function updatePad(event) { const dx = event.clientX - (rect.left + rect.width / 2); const dy = event.clientY - (rect.top + rect.height / 2); const length = Math.min(rect.width * .34, Math.hypot(dx, dy)); const angle = Math.atan2(dy, dx); input.move.x = Math.cos(angle) * length / (rect.width * .34); input.move.y = Math.sin(angle) * length / (rect.width * .34); pad.firstElementChild.style.transform = `translate(${input.move.x * 30}px,${input.move.y * 30}px)`; } $('firePad').addEventListener('pointerdown', () => { input.fireTouch = true; }); $('firePad').addEventListener('pointerup', () => { input.fireTouch = false; }); }

  $('playButton').addEventListener('click', startGame); $('againButton').addEventListener('click', startGame); $('pauseButton').addEventListener('click', pauseGame); $('resumeButton').addEventListener('click', resumeGame); $('restartButton').addEventListener('click', startGame); $('resultMenuButton').addEventListener('click', () => { sounds.click(); setScreen('menu'); syncMenu(); }); $('pauseMenuButton').addEventListener('click', () => { sounds.click(); setScreen('menu'); syncMenu(); }); $('instructionsButton').addEventListener('click', () => { sounds.click(); setScreen('instructions'); }); $('settingsButton').addEventListener('click', () => { sounds.click(); syncSettings(); setScreen('settings'); }); document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => { sounds.click(); setScreen('menu'); })); $('soundToggle').addEventListener('click', () => { settings.sound = !settings.sound; store.set('sound', settings.sound); syncSettings(); if (settings.sound) sounds.click(); }); $('motionToggle').addEventListener('click', () => { settings.motion = !settings.motion; store.set('motion', settings.motion); syncSettings(); }); document.querySelectorAll('[data-difficulty]').forEach(button => button.addEventListener('click', () => { settings.difficulty = button.dataset.difficulty; store.set('difficulty', settings.difficulty); syncSettings(); sounds.click(); }));

  function frame(time) { const dt = Math.min(.033, (time - lastTime) / 1000 || 0); lastTime = time; update(dt); draw(); requestAnimationFrame(frame); }
  resize(); syncMenu(); syncSettings(); bindTouch(); document.body.classList.toggle('mobile', 'ontouchstart' in window); requestAnimationFrame(frame);
})();
